### ISSUE TITLE
Error installing on OSX

### ISSUE THREAD

**Issue by lastcoolnameleft** [noelbundick/azure-cli-extension-noelbundick#13]
I encounter the following error when I install on OSX.  I'm using Pip3, which *hopefully shouldn't* matter, but might contribute to the dependency issues.

I have been able to successfully install in Azure Cloud Shell.

```
➜  azure-cli-extension-noelbundick # az --version
azure-cli (2.0.33)
...
Extensions:
dev-spaces-preview (0.1.3)

Python location '/usr/local/opt/python/bin/python3.6'
Extensions directory '/Users/thfalgou/.azure/devcliextensions'

Python (Darwin) 3.6.5 (default, Apr 25 2018, 14:23:58)
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)]

Legal docs and information: aka.ms/AzureCliLegal

➜  azure-cli-extension-noelbundick # pip3 install --upgrade --target ~/.azure/devcliextensions/noelbundick $PWD/src/noelbundick
Processing ./src/noelbundick
Building wheels for collected packages: noelbundick
  Running setup.py bdist_wheel for noelbundick ... done
  Stored in directory: /private/var/folders/w2/z8990m3939q7hwf1hlxbjnwm0000gn/T/pip-ephem-wheel-cache-6_dcfzyd/wheels/ae/93/5f/8e60d217e8637d214fa42662b0714585da7aab071a35a64da0
Successfully built noelbundick
azure-mgmt-storage 0.30.0rc6 has requirement azure-common[autorest]==1.1.4, but you'll have azure-common 1.1.11 which is incompatible.
azure-mgmt-scheduler 1.0.0 has requirement azure-common[autorest]==1.1.4, but you'll have azure-common 1.1.11 which is incompatible.
azure-mgmt-resource 0.30.0rc6 has requirement azure-common[autorest]==1.1.4, but you'll have azure-common 1.1.11 which is incompatible.
azure-mgmt-redis 1.0.0 has requirement azure-common[autorest]==1.1.4, but you'll have azure-common 1.1.11 which is incompatible.
azure-mgmt-network 0.30.0rc6 has requirement azure-common[autorest]==1.1.4, but you'll have azure-common 1.1.11 which is incompatible.
azure-mgmt-logic 1.0.0 has requirement azure-common[autorest]==1.1.4, but you'll have azure-common 1.1.11 which is incompatible.
azure-mgmt-keyvault 0.30.0rc6 has requirement azure-common[autorest]==1.1.4, but you'll have azure-common 1.1.11 which is incompatible.
azure-mgmt-compute 0.30.0rc6 has requirement azure-common[autorest]==1.1.4, but you'll have azure-common 1.1.11 which is incompatible.
azure-mgmt-batch 1.0.0 has requirement azure-common[autorest]==1.1.4, but you'll have azure-common 1.1.11 which is incompatible.
azure-batch 1.0.0 has requirement azure-common[autorest]==1.1.4, but you'll have azure-common 1.1.11 which is incompatible.
Installing collected packages: noelbundick
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/basecommand.py", line 228, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 335, in run
    use_user_site=options.use_user_site,
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/req/__init__.py", line 49, in install_given_reqs
    **kwargs
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 748, in install
    use_user_site=use_user_site, pycompile=pycompile,
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 961, in move_wheel_files
    warn_script_location=warn_script_location,
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/wheel.py", line 216, in move_wheel_files
    prefix=prefix,
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/locations.py", line 165, in distutils_scheme
    i.finalize_options()
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/install.py", line 248, in finalize_options
    "must supply either home or prefix/exec-prefix -- not both")
distutils.errors.DistutilsOptionError: must supply either home or prefix/exec-prefix -- not both
```

**Comment by lastcoolnameleft** [comment]
I've been able to verify that installing via URL works:

```
➜  az extension add --source https://github.com/noelbundick/azure-cli-extension-noelbundick/releases/download/v0.0.8/noelbundick-0.0.8-py2.py3-none-any.whl

Are you sure you want to install this extension? (y/n): y
```

**Comment by noelbundick** [comment]
Cool! I guess it's a pip thing? Seems related - not sure if this is a thing you could try? Or if it's something I could add to fix or if you need to do it
https://stackoverflow.com/questions/24257803/distutilsoptionerror-must-supply-either-home-or-prefix-exec-prefix-not-both

**Comment by noelbundick** [comment]
Gonna close this one out since you're up & running. If you ever decide to develop/build locally instead of using a release - let's open/reopen an issue :)

**Comment by lastcoolnameleft** [comment]
Works for me. Thanks!
