### ISSUE TITLE
Failed to load `noelbundick` extension

### ISSUE THREAD

**Issue by khenidak** [noelbundick/azure-cli-extension-noelbundick#7]
Here is the output of 

`az group list --debug`

```
Unable to load extension 'noelbundick'. Use --debug for more information.
Traceback (most recent call last):
  File "/home/khenidak/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/__init__.py", line 175, in _update_command_table_from_extensions
    extension_command_table = _load_extension_command_loader(self, args, ext_mod)
  File "/home/khenidak/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 581, in _load_extension_command_loader
    return _load_command_loader(loader, args, ext, '')
  File "/home/khenidak/lib/azure-cli/local/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 567, in _load_command_loader
    command_table = command_loader.load_command_table(args)
  File "/home/khenidak/.azure/cliextensions/noelbundick/azext_noelbundick/__init__.py", line 29, in load_command_table
    m.load_command_table(self, args)
  File "/home/khenidak/.azure/cliextensions/noelbundick/azext_noelbundick/ad.py", line 9, in load_command_table
    custom = CliCommandType(operations_tmpl='{}#{{}}'.format(__loader__.name))
NameError: global name '__loader__' is not defined
```

to be fair, I have another issue 
```
/home/khenidak/lib/azure-cli/local/lib/python2.7/site-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.23) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
```

Which i am trying to figure out if it is related or not

**Comment by khenidak** [comment]
Can confirm that the dependency error is not related, i fixed it and it is load error above is still there

**Comment by noelbundick** [comment]
I bet this is a Python 2/3 thing that I'm not handling properly. Will check with the resident Python errors & fix this in next release

I see you're on 2.0.35. What's your platform/install method? Mac + homebrew?

**Comment by khenidak** [comment]
Linux. Manual as cli install

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by noelbundick** [comment]
https://github.com/noelbundick/azure-cli-extension-noelbundick/releases/tag/v0.0.7

Can you try latest? Fixed `__loader__` error & added `az self-destruct arm` to schedule delete of existing resources

**Comment by khenidak** [comment]
works as advertised. Thanks!
